spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}
  validate-in-seconds: 7776000

fcm:
  key:
    path: ${FCM_KEY_PATH}